### PR TITLE
Remove GWT dependency.

### PR DESCRIPTION
**Pull request by nicks**
Now there's a separate artifact for the jsinterop annotations. yay! :)

### CODE REVIEW

**Comment by jamestyrrell** [comment]
The is excellent, A++ would merge 👍

**Comment by nicks** [comment]
Hi @mikesamuel ! Anything I can do to help this get merged? It should make our jars a lot smaller.

**Comment by mikesamuel** [comment]
Will do.  Sorry for the delay.  I did not have a watch.

**Comment by mikesamuel** [comment]
TLDR: will release Monday or Tuesday.

This patch has been committed internally.  The thing that has delayed releasing it has been some work to upgrade to a modern version of protobuf.   https://github.com/comoyo/commons/pull/46 went in smoothly enough, but that exposed a flaw in a workaround to get the opensource tests running on our distributed test infrastructure.  That's fixed now, so I should put out a release shortly.

**Comment by mikesamuel** [comment]
Released as https://github.com/google/safe-html-types/releases/tag/release-1.0.6 which should show on maven central soon.

**Pull request closed without merging**
