### PR TITLE
Apply @CheckReturnValue annotation just to relevant types instead of entire package

### LINKED ISSUE #8: Package should not be annotated @CheckReturnValue -- generated protobuf code fails Error Prone checks
Package `com.google.common.html.types` is annotated with `@CheckReturnValue`: https://github.com/google/safe-html-types/blob/abccc1eb91b4dd1ca817c61f3c743fb3a3320fb6/types/src/main/java/com/google/common/html/types/package-info.java#L23

This causes builds that enforce the annotation (like [Error Prone](http://errorprone.info/bugpattern/CheckReturnValue)) to fail on generated protocol buffers which reference the safe html types defined in this repository.

Example: 
```proto
import "webutil/html/types/html.proto";

message Test {
  optional webutil.html.types.SafeUrlProto url_field = 1;
}
```

Attempting to compile with error prone will fail on the generated java protobuf code with a message like:

```
error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
                subBuilder.mergeFrom(urlField_);
                                    ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean 'subBuilder = subBuilder.mergeFrom(urlField_);'?
```
```
error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    com.google.common.html.types.Html.getDescriptor();
                                                   ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?
```

Because the protocol buffer messages reside in the same `java_package` `com.google.common.html.types`, I don't believe there's a quick fix for this other than removing the annotation from from the package and instead annotating all classes in `types/src/main/java/com/google/common/html/types` individually. 

Update: This actually also affects several of the non-protobuf classes--`@CheckReturnValue` shouldn't apply to the following builders:
* `SafeHtmlBuilder`
* `SafeStyleBuilder`
* `TrustedResourceUrlBuilder`

### PR DESCRIPTION
**Pull request by orischwartz**
fixes #8

* Builder types `SafeHtmlBuilder`, `SafeStyleBuilder`, `TrustedResourceUrlBuilder` should not be subject to `CheckReturnValue`
* Use of generated protocol buffers code should not be subject to `CheckReturnValue`.

### CODE REVIEW

**Comment by mikesamuel** [comment]
Thanks for the patch.  If I understand the bug, a package-level annotation is causing problems.  I don't see any deletion of the package-level annotation though.

**Comment by mikesamuel** [comment]
My mistake.  I see that you've deleted the entirety of `package-info.java`.  I'll pull this patch internally and close this PR when I push it back out.

**Comment by mikesamuel** [comment]
Pulled internally where it's queued for review.  Will probably push a new version to github and maven early next week.

**Comment by orischwartz** [comment]
Thanks, no rush. One easy workaround is to just make the error-prone check a warning instead of an error with the `-Xep:CheckReturnValue:WARN` compiler arg.

**Comment by orischwartz** [comment]
Fixed via 7e6e902e52b206d1c369cc834f98e93911613aee

**Pull request closed without merging**
